..btn_dateFormat_editFormat <- function(session, rv_DateFormat){
  rv_DateFormat$AddEdit <- "Edit"
  updateTextInput(session = session, 
                  inputId = "txt_dateFormat_formatName", 
                  value = rv_DateFormat$SelectedDateFormat$FormatName)
  updateTextInput(session = session, 
                  inputId = "txt_dateFormat_description", 
                  value = rv_DateFormat$SelectedDateFormat$Description)
  updateTextInput(session = session, 
                  inputId = "txt_dateFormat_formatCode", 
                  value = rv_DateFormat$SelectedDateFormat$FormatCode)
  updateNumericInput(session = session, 
                     inputId = "num_dateFormat_incrementStart", 
                     value = rv_DateFormat$SelectedDateFormat$IncrementStart)
  updateSelectInput(session = session, 
                    inputId = "sel_dateFormat_incrementStartUnit", 
                    selected = rv_DateFormat$SelectedDateFormat$IncrementStartUnit)
  updateNumericInput(session = session, 
                     inputId = "num_dateFormat_incrementEnd", 
                     value = rv_DateFormat$SelectedDateFormat$IncrementEnd)
  updateSelectInput(session = session, 
                    inputId = "sel_dateFormat_incrementEndUnit", 
                    selected = rv_DateFormat$SelectedDateFormat$IncrementEndUnit)
  updateCheckboxInput(session = session, 
                      inputId = "chk_dateFormat_isActive", 
                      value = rv_DateFormat$SelectedDateFormat$IsActive)
  toggleModal(session = session, 
              modalId = "modal_dateFormat_addEdit", 
              toggle = "open")
}
