..dateFormat_addFormat <- function(session, rv_DateFormat){
  rv_DateFormat$AddEdit <- "Add"
  updateTextInput(session = session, 
                  inputId = "txt_dateFormat_formatName", 
                  value = "")
  updateTextInput(session = session, 
                  inputId = "txt_dateFormat_description", 
                  value = "")
  updateTextInput(session = session, 
                  inputId = "txt_dateFormat_formatCode", 
                  value = "")
  updateNumericInput(session = session, 
                     inputId = "num_dateFormat_incrementStart", 
                     value = 0)
  updateSelectInput(session = session, 
                    inputId = "sel_dateFormat_incrementStartUnit", 
                    selected = "Second")
  updateNumericInput(session = session, 
                     inputId = "num_dateFormat_incrementEnd", 
                     value = 0)
  updateSelectInput(session = session, 
                    inputId = "sel_dateFormat_incrementEndUnit", 
                    selected = "Second")
  updateCheckboxInput(session = session, 
                      inputId = "chk_dateFormat_isActive", 
                      value = TRUE)
  toggleModal(session = session, 
              modalId = "modal_dateFormat_addEdit", 
              toggle = "open")
}
