args <- commandArgs(trailingOnly = TRUE)

branch <- args[1]

# options(test_email_subj_prefix = "[TEST]: ",
#         test_email_prefix = paste0("This e-mail is a test generated by the ",
#                                    "BGCAPP Reporting Application.  Please disregard ",
#                                    "the content below--you do not need to take ",
#                                    "any action\n\n"),
#         app_email = "live") # for testing and production
#         # app_email = "bnutter@bechtel.us") # For development

library(reportManager)

SETTINGS <- queryApplicationSetting()

SMTP <- SETTINGS$SettingValue[SETTINGS$SettingKey == "smtpServer"]

if (!is.na(SMTP)){
  options(RM_smtpServer = SMTP)
}

# Set the ZIP Executable location on startup 

ZIP <- SETTINGS$SettingValue[SETTINGS$SettingKey == "zipExecutable"]

if (!is.na(ZIP) && trimws(ZIP) != ""){
  Sys.setenv("R_ZIPCMD" = ZIP)
}

# Set the Pandoc directory location on startup

PANDOC <- trimws(SETTINGS$SettingValue[SETTINGS$SettingKey == "pandocDirectory"])

if (!isTRUE(length(PANDOC) == 0 | PANDOC %in% c(NA, ""))){
  rmarkdown::find_pandoc(dir = PANDOC, 
                         cache = FALSE)
  Sys.setenv(PATH = PANDOC)
  Sys.setenv(RSTUDIO_PANDOC = PANDOC)
}


ToDistribute <- getInstanceToAutoDistribute()

message("Reports to Distribute This Iteration--------------------")

ToDistribute

for (i in seq_len(nrow(ToDistribute))){
  addDistributeSubmitReportOutsideApp(
    report_template_oid = ToDistribute$ParentReportTemplateOID[i], 
    report_instance_oid = ToDistribute$ReportInstanceOID[i], 
    smash_types = c("daams", "minicams"), 
    add_to_filestream = ToDistribute$IsAddToArchive[i],
    output_format = ToDistribute$ReportFormat[i]
  )
}
