#' @name addEditReportTemplate
#' @title Add or Edit ReportTemplate Objects
#' 
#' @description Enables the user to add ReportTemplate objects or edit
#'   existing objects. Only the properties stored directly on 
#'   the ReportTemplate object are edited with this function.
#'   
#' @param oid `integerish(0/1)`. The OID of the ReportTemplate object to be
#'   edited. Use `numeric(0)` to add a new object. 
#' @param template_name `character(1)`. The internal reference name of the 
#'   report template. No more than 50 characters.
#' @param template_directory `character(1)`. The directory in which the 
#'   report template files are stored. No more than 50 characters.
#' @param template_file `character(1)`. The primary template file that 
#'   directs the progress of the report template. No more than 50 characters.
#' @param title `character(1)`. The title to display on the report. No more
#'   than 200 characters.
#' @param title_size `character(1)`. The size of the font to use when 
#'   rendering the title. 
#' @param include_toc `logical(1)`. When `TRUE`, a table of contents will be
#'   included in the report. 
#' @param default_email `character(1)`. The default text to display in the 
#'   e-mail submission dialog box. 
#' @param is_signature_required `logical(1)`. When `TRUE`, the template 
#'   requires signatures before it can be delivered to external users. 
#' @param is_active `logical(1)`. When `TRUE`, the template is flagged for
#'   active use.
#' @param logo_oid `integerish(0/1)`. The OID of the logo to display when
#'   rendering the title. 
#' @param supporting_data_file `character(1)`. The name of the supporting 
#'   data file that may be generated by the template. This is used to find 
#'   the file in the directory where reports are generated. May be no more than
#'   150 characters.
#' @param is_include_data `logical(1)`. WHEN `TRUE`, the supporting data will 
#'   be included with the report when distributed internally or submitted
#'   to internal clients.
#' @param event_user `integerish(1)`. The OID of the user performing the 
#'   action.
#'   
#' @export

addEditReportTemplate <- function(oid = numeric(0), 
                                  template_name,
                                  template_directory, 
                                  template_file, 
                                  title, 
                                  title_size, 
                                  include_toc = FALSE, 
                                  default_email = "",
                                  is_signature_required = FALSE, 
                                  is_active = TRUE, 
                                  logo_oid = numeric(0), 
                                  date_reporting_format = 1,
                                  supporting_data_file = "SupportingData.csv",
                                  is_include_data = FALSE,
                                  event_user){
  # Argument Validation ---------------------------------------------
  coll <- checkmate::makeAssertCollection()
  
  checkmate::assertIntegerish(x = oid, 
                              max.len = 1, 
                              add = coll)
  
  checkmate::assertString(x = template_name, 
                          max.chars = 50, 
                          add = coll)
  
  checkmate::assertString(x = template_directory, 
                          max.chars = 50, 
                          add = coll)
  
  checkmate::assertString(x = template_file, 
                          max.chars = 50, 
                          add = coll)
  
  checkmate::assertString(x = title, 
                          max.chars = 200, 
                          add = coll)
  
  title_size <- checkmate::matchArg(x = title_size, 
                                    choices = unname(FONT_SIZES), 
                                    .var.name = "title_size",
                                    add = coll)
  
  checkmate::assertLogical(x = include_toc, 
                           len = 1,
                           add = coll)
  
  checkmate::assertString(x = default_email, 
                          max.chars = 1000, 
                          add = coll)
  
  checkmate::assertLogical(x = is_signature_required, 
                           len = 1, 
                           add = coll)
  
  checkmate::assertLogical(x = is_active, 
                           len = 1, 
                           add = coll)
  
  checkmate::assertIntegerish(x = logo_oid, 
                              max.len = 1, 
                              add = coll)
  
  checkmate::assertIntegerish(x = date_reporting_format, 
                              len = 1, 
                              add = coll)
  
  checkmate::assertIntegerish(x = event_user, 
                              len = 1, 
                              add = coll)
  
  checkmate::assertString(x = supporting_data_file, 
                          max.chars = 150, 
                          add = coll)
  
  checkmate::assertLogical(x = is_include_data, 
                           len = 1, 
                           add = coll)
  
  checkmate::reportAssertions(coll)
  
  # Functionality ---------------------------------------------------
  
  conn <- connectToReportManager()
  on.exit({ DBI::dbDisconnect(conn) })
  
  template_name <- trimws(template_name)
  template_directory <- trimws(template_directory)
  template_file <- trimws(template_file)
  title <- trimws(title)
  title_size <- trimws(title_size)
  default_email <- trimws(default_email)
  
  event_time <- Sys.time()
  
  AddEditData <- data.frame(TemplateName = template_name, 
                            TemplateDirectory = template_directory, 
                            TemplateFile = template_file, 
                            Title = title, 
                            TitleSize = title_size, 
                            IncludeTableOfContents = as.numeric(include_toc),
                            DefaultEmailText = default_email,
                            IsSignatureRequired = as.numeric(is_signature_required), 
                            IsActive = as.numeric(is_active), 
                            LogoFileArchive = logo_oid, 
                            DateReportingFormat = date_reporting_format, 
                            SupportingDataFile = supporting_data_file, 
                            IsIncludeData = is_include_data)
  
  EventList <- 
    data.frame(EventUser = rep(event_user, 14), 
               EventType = c("Add", 
                             if (include_toc) "SetIncludeTocTrue" else "SetIncludeTocFalse",
                             if (is_signature_required) "SetSignatureRequiredTrue" else "SetSignatureRequiredFalse", 
                             if (is_active) "Activate" else "Deactivate",
                             "EditTemplateFolder", 
                             "EditTemplateFile", 
                             "EditTitle", 
                             "EditTitleSize",
                             "EditDefaultEmailText",
                             "EditLogoFile", 
                             "EditDateReportingFormat", 
                             "EditTemplateName", 
                             "EditSupportingDataFile", 
                             "EditIsIncludeData"), 
               EventDateTime = rep(format(event_time, 
                                          format = "%Y-%m-%d %H:%M:%S"), 14), 
               NewValue = c("", 
                            include_toc,
                            is_signature_required, 
                            is_active, 
                            template_directory, 
                            template_file, 
                            title, 
                            title_size, 
                            default_email,
                            logo_oid, 
                            date_reporting_format, 
                            template_name, 
                            supporting_data_file, 
                            is_include_data))
  
  if (length(oid) == 0){
    
    OID <- insertRecord(AddEditData, 
                        table_name = "ReportTemplate")
    
    EventList$ParentReportTemplate <- rep(OID$OID, 
                                          nrow(EventList))
  } else {
    EventList <- .addEditReportTemplate_editedEventList(EventList = EventList,
                                                        oid       = oid,
                                                        conn      = conn)
    
    if (nrow(EventList) > 0){
      updateRecord(data = AddEditData, 
                   where_data = data.frame(OID = oid), 
                   table_name = "ReportTemplate")
    }
  }
  
  if (nrow(EventList)){
    insertRecord(EventList, 
                 table_name = "ReportTemplateEvent", 
                 return_oid = FALSE)
  }
}

# Unexported --------------------------------------------------------

.addEditReportTemplate_editedEventList <- function(EventList, 
                                                   oid,
                                                   conn){
  EventList$ParentReportTemplate <- rep(oid, 
                                        nrow(EventList))
  EventList <- EventList[!EventList$EventType == "Add", ]
  ThisReportTemplate <- queryReportTemplate(oid)

  CurrentValue <- c(ThisReportTemplate$IncludeTableOfContents, 
                    ThisReportTemplate$IsSignatureRequired, 
                    ThisReportTemplate$IsActive, 
                    ThisReportTemplate$TemplateDirectory, 
                    ThisReportTemplate$TemplateFile, 
                    ThisReportTemplate$Title, 
                    ThisReportTemplate$TitleSize, 
                    ThisReportTemplate$DefaultEmailText,
                    ThisReportTemplate$LogoFileArchive,
                    ThisReportTemplate$DateReportingFormat, 
                    ThisReportTemplate$TemplateName, 
                    ThisReportTemplate$SupportingDataFile, 
                    ThisReportTemplate$IsIncludeData)
  
  EventList[compareValues(CurrentValue, EventList$NewValue), ]
}
